receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1500
  resource:
    attributes:
      - key: environment
        value: "production"
        action: upsert
      - key: service.version
        value: "2.0.0"
        action: upsert

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "http://jaeger:14250"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "sre_agent"
    const_labels:
      label1: value1
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    num_workers: 4
    timeout: 30s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
  pprof:
    endpoint: "0.0.0.0:1777"
  zpages:
    endpoint: "0.0.0.0:55679"

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter, resource]
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter, resource]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch, memory_limiter, resource]
      exporters: [logging, elasticsearch] 